use crate::lalrpop_frontend::{BinOp, RawAst};

grammar;

pub Expr: RawAst = {
    <l:Expr> "+" <r:Factor> => RawAst::BinOp(Box::new(l), BinOp::Add, Box::new(r)),
    <l:Expr> "-" <r:Factor> => RawAst::BinOp(Box::new(l), BinOp::Sub, Box::new(r)),
    Factor,
};

Factor: RawAst = {
    <l:Factor> "*" <r:Term> => RawAst::BinOp(Box::new(l), BinOp::Mul, Box::new(r)),
    <l:Factor> "/" <r:Term> => RawAst::BinOp(Box::new(l), BinOp::Div, Box::new(r)),
    Term,
};

Term: RawAst = {
    Num => RawAst::Number(<>),
    Ident => RawAst::Var(<>),
    "if" <c:Expr> "{" <t:Expr> "}" "else" "{" <e:Expr> "}" =>
        RawAst::If(Box::new(c), Box::new(t), Box::new(e)),
    "(" <Expr> ")",
};

Num: f64 = r"[0-9]+(\.[0-9]+)?" => <>.parse().unwrap();
Ident: String = r"[a-zA-Z_][a-zA-Z0-9_]*" => <>.to_string();
